from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from typing import List, Dict, Any, Optional

from app.core.database import get_db
from app.api.planner import fetch_enriched_areas_data
from app.planner.forecast import generate_multi_period_forecast
from app.models.schema import User
from app.core.auth import get_current_user

router = APIRouter(prefix="/forecast", tags=["Forecasting"])

@router.get("", response_model=List[Dict[str, Any]])
def get_multi_period_forecasts(
    area_id: Optional[str] = Query(default=None, description="Optional area_id filter"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Returns multi-period seasonal demand and disease risk forecasts generated by Exponential Smoothing.
    """
    areas_data = fetch_enriched_areas_data(db)
    if area_id:
        areas_data = [a for a in areas_data if a["area_id"] == area_id]

    forecasts = generate_multi_period_forecast(areas_data)
    return forecasts
